service: evote-poc-server
frameworkVersion: '3'

custom:
  config:
    lambda:
      timeout: 15       # seconds
      memorySize: 128   # MB

provider:
  name: aws
  region: ap-southeast-1      # Singapore
  runtime: provided.al2023    # OS-only Runtime
  architecture: arm64
  environment:
    KALEIDO_REST_API_ENDPOINT: "https://a0z8wc2w78-a0ve7t5vxf-connect.au0-aws-ws.kaleido.io"
    KALEIDO_AUTH_TOKEN: ${env:KALEIDO_AUTH_TOKEN}

plugins:
  - serverless-iam-roles-per-function

package:
  individually: true
  patterns:
    - '!./**'

functions:
  read-vote: ${file(./read-vote/serverless.yml):READ-VOTE}
  count-votes: ${file(./count-votes/serverless.yml):COUNT-VOTES}
  register: ${file(./register/serverless.yml):REGISTER}
  submit-vote: ${file(./submit-vote/serverless.yml):SUBMIT-VOTE}