COUNT-VOTES:
  handler: bootstrap
  timeout: ${self:custom.config.lambda.timeout}
  memorySize: ${self:custom.config.lambda.memorySize}
  events:
    - http:
        path: /count-votes
        method: post
  environment:
    PAILLIER_PRIVATE_KEY: ${env:PAILLIER_PRIVATE_KEY}
    KALEIDO_AUTH_TOKEN: ${env:KALEIDO_AUTH_TOKEN}
  package:
    artifact: count-votes.zip