name: Deploy eVote POC Lambdas

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lambda-deployment.yml'
      - 'scripts/**'
      - 'app/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'
          cache-dependency-path: go.sum

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Serverless Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PAILLIER_PRIVATE_KEY: ${{ secrets.PAILLIER_PRIVATE_KEY }}
          KALEIDO_AUTH_TOKEN: ${{ secrets.KALEIDO_AUTH_TOKEN }}
          STAGE: dev
        run: |
          echo "Installing Serverless"
          pnpm install serverless -g
          pnpm install serverless-iam-roles-per-function
          ./scripts/build_and_deploy_lambdas.sh