name: Deploy eVote POC Lambdas

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lambda-deployment.yml'
      - 'scripts/**'
      - 'app/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'
        run: go version

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Serverless Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          STRIPE_TOKEN: ${{ secrets.STRIPE_TOKEN }}
          STAGE: dev
        run: |
          echo "Installing Serverless"
          pnpm install serverless -g
          ./scripts/build_and_deploy_lambdas.sh