READ-VOTE:
  handler: bootstrap
  timeout: ${self:custom.config.lambda.timeout}
  memorySize: ${self:custom.config.lambda.memorySize}
  events:
    - http:
        path: /read-vote
        method: post
        cors: true
  environment:
    PAILLIER_PRIVATE_KEY: ${env:PAILLIER_PRIVATE_KEY}
    KALEIDO_AUTH_TOKEN: ${env:KALEIDO_AUTH_TOKEN}
  package:
    artifact: read-vote.zip
