READ-VOTE:
  handler: bootstrap
  timeout: ${self:custom.config.lambda.timeout}
  memorySize: ${self:custom.config.lambda.memorySize}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/voter-credentials"
  events:
    - http:
        path: /read-vote
        method: post
        cors:
          origin: "*"
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
  environment:
    PAILLIER_PRIVATE_KEY: ${env:PAILLIER_PRIVATE_KEY}
  package:
    artifact: read-vote.zip