READ-VOTE:
  handler: bootstrap
  timeout: ${self:custom.config.lambda.timeout}
  memorySize: ${self:custom.config.lambda.memorySize}
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - dynamodb:GetItem
  #       - dynamodb:Query
  #     Resource:
  events:
    - http:
        path: /read-vote
        method: post
  environment:
    PAILLIER_PRIVATE_KEY: ${env:PAILLIER_PRIVATE_KEY}
    KALEIDO_AUTH_TOKEN: ${env:KALEIDO_AUTH_TOKEN}
  package:
    artifact: read-vote.zip